ALTER TABLE banners ADD COLUMN desktop_position_x INTEGER NOT NULL DEFAULT 50;
ALTER TABLE banners ADD COLUMN desktop_position_y INTEGER NOT NULL DEFAULT 50;
ALTER TABLE banners ADD COLUMN desktop_scale INTEGER NOT NULL DEFAULT 100;
ALTER TABLE banners ADD COLUMN mobile_position_x INTEGER NOT NULL DEFAULT 50;
ALTER TABLE banners ADD COLUMN mobile_position_y INTEGER NOT NULL DEFAULT 50;
ALTER TABLE banners ADD COLUMN mobile_scale INTEGER NOT NULL DEFAULT 100;
