import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const worker=await readFile(new URL('../cloudflare-dashboard/worker.js',import.meta.url),'utf8');
const access=await readFile(new URL('../assets/js/admin-access.js',import.meta.url),'utf8');
const config=await readFile(new URL('../assets/js/config.js',import.meta.url),'utf8');
const migration=await readFile(new URL('../cloudflare-dashboard/admin-trusted-devices-upgrade.sql',import.meta.url),'utf8');
const has=value=>assert.ok(worker.includes(value),`missing: ${value}`);
test('1 permanent device on same IP',()=>{has('d.token_hash=?');has('datetime(d.expires_at)>CURRENT_TIMESTAMP')});
test('2 permanent device on different IP',()=>{has("row.lastIp!==ip");has("'NEW_NETWORK_DETECTED'")});
test('3 consecutive IP changes do not create enrollment',()=>{assert.doesNotMatch(worker.slice(worker.indexOf('async function validHybridGrant'),worker.indexOf('async function verifyActorReauth')),/admin_trusted_device_requests/)});
test('4 logout does not revoke device',()=>{const body=worker.slice(worker.indexOf('async function logout'),worker.indexOf('async function sessionStatus'));assert.doesNotMatch(body,/admin_trusted_devices|shoplab_trusted_device/)});
test('5 expired session is rejected',()=>has('datetime(s.expires_at)>CURRENT_TIMESTAMP'));
test('6 revoked device is rejected',()=>has('d.revoked_at IS NULL'));
test('7 deleted device cannot match token',()=>has('FROM admin_trusted_devices d'));
test('8 inactive collaborator is rejected',()=>has('c.is_active=1'));
test('9 missing cookie is rejected',()=>has('if(!token||!session)return false'));
test('10 forged cookie is hashed and rejected',()=>has('await sha256(token)'));
test('11 invalid token requires matching hash',()=>has('d.token_hash=?'));
test('12 routine network access does not rotate token',()=>{const body=worker.slice(worker.indexOf('async function grantNewNetworkAccess'),worker.indexOf('async function createTrustedDevice'));assert.doesNotMatch(body,/token_hash=|newToken/)});
test('13 no cookie-loss window during network update',()=>{has('UPDATE admin_trusted_devices SET last_used_at=CURRENT_TIMESTAMP,last_ip=?')});
test('14 parallel requests keep the same device credential',()=>{const body=worker.slice(worker.indexOf('async function validHybridGrant'),worker.indexOf('async function verifyActorReauth'));assert.doesNotMatch(body,/UPDATE\s+admin_trusted_devices\s+SET\s+token_hash=/)});
test('15 new browser has no trusted cookie',()=>has("cookie(req,'shoplab_trusted_device')"));
test('16 same browser on new network is audited',()=>has("{previousIp:row.lastIp||null}"));
test('17 unknown device on authorized IP still reaches login',()=>has('ipMatchesAny(ip,recoveryNetworks(env))'));
test('18 unknown device on unauthorized IP is denied',()=>has("'ADMIN_IP_NOT_AUTHORIZED'"));
test('19 owner may change IP with bound owner session',()=>has("d.actor_type='owner' AND d.actor_id='owner' AND s.collaborator_id IS NULL"));
test('20 collaborator changes IP without a new request',()=>has("d.actor_type='collaborator' AND s.collaborator_id=d.actor_id"));
test('21 admin-access recognizes existing device',()=>{assert.match(access,/deviceMatchesActor/);has('async function adminAccessStatus')});
test('22 admin API remains protected',()=>has("url.pathname.startsWith('/api/v1/admin/')"));
test('23 RBAC remains mandatory',()=>has('actor.permissions.includes(permission)'));
test('24 critical reauthentication remains enabled',()=>has('verifyActorReauth'));
test('25 recovery IPs remain enabled',()=>has('ADMIN_RECOVERY_IPS'));
test('cookie covers admin gate securely',()=>{assert.match(worker,/shoplab_trusted_device=.*Path=\/; HttpOnly; Secure; SameSite=Lax/);assert.ok(config.includes("admin.shoplab.com.br")&&config.includes("location.origin"))});
test('hybrid is device-first and strict remains available',()=>{assert.match(migration,/strict','hybrid/);has("settings?.accessMode!=='hybrid'")});
