import {sendEmail} from './provider.js';
import {emailBrandingHead,emailLogo} from './branding.js';

export const INTEREST_WEIGHTS=Object.freeze({NEWS_VIEW:1,NEWS_ENGAGED_VIEW:3,NEWS_COMPLETED_READING:4,SEARCH_TOPIC:4,PRODUCT_VIEW:2,REPEATED_CATEGORY_VIEW:3,COMPARISON:6,AFFILIATE_CLICK:8,EMAIL_OPEN:1,EMAIL_CLICK:6});
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,160);
const json=(data,status=200)=>new Response(JSON.stringify({success:status<400,data:status<400?data:null,error:status<400?null:data}),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const publicOrigin=env=>String(env.PUBLIC_SITE_URL||'https://shoplab.com.br').replace(/\/+$/,'');

async function token(env,subscriber){
  const secret=String(env.NEWSLETTER_TOKEN_SECRET||'');if(secret.length<32)throw Error('NEWSLETTER_TOKEN_SECRET_NOT_CONFIGURED');
  const payload=`${subscriber.id}.${subscriber.userId}.${subscriber.email.toLowerCase()}`,key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']),signature=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(payload));
  return `${subscriber.id}.${[...new Uint8Array(signature)].map(x=>x.toString(16).padStart(2,'0')).join('')}`;
}
async function subscriberFromToken(env,value){
  const [id,provided]=String(value||'').split('.');if(!id||!/^[a-f0-9]{64}$/.test(provided||''))return null;
  const row=await env.DB.prepare('SELECT id,user_id userId,email FROM newsletter_subscribers WHERE id=?').bind(id).first();if(!row)return null;
  const expected=(await token(env,row)).split('.')[1],a=new TextEncoder().encode(expected),b=new TextEncoder().encode(provided);let diff=a.length^b.length;for(let i=0;i<Math.min(a.length,b.length);i++)diff|=a[i]^b[i];return diff?null:row;
}
export async function newsletterPreferences(req,env,user){
  if(!user)return json({code:'UNAUTHORIZED',message:'Entre para gerenciar a newsletter.'},401);
  const profile=await env.DB.prepare('SELECT email FROM user_profiles WHERE user_id=?').bind(user.id).first(),email=String(profile?.email||user.email||'').trim().toLowerCase();
  if(req.method==='GET'){const row=await env.DB.prepare('SELECT status,personalization_enabled personalizationEnabled,subscribed_at subscribedAt,unsubscribed_at unsubscribedAt FROM newsletter_subscribers WHERE user_id=?').bind(user.id).first();return json(row||{status:'unsubscribed',personalizationEnabled:1});}
  if(req.method!=='PUT')return json({code:'METHOD_NOT_ALLOWED',message:'Método não permitido.'},405);
  const body=await req.json(),active=body.active!==false,personalization=body.personalizationEnabled!==false;if(!email||!/^\S+@\S+\.\S+$/.test(email))return json({code:'INVALID_EMAIL',message:'Sua conta precisa ter um e-mail válido.'},422);
  await env.DB.prepare(`INSERT INTO newsletter_subscribers(id,user_id,email,status,personalization_enabled,subscribed_at,unsubscribed_at,last_site_activity_at,engagement_state) VALUES(?,?,?, ?,?,CURRENT_TIMESTAMP,?,CURRENT_TIMESTAMP,'active') ON CONFLICT(user_id) DO UPDATE SET email=excluded.email,status=excluded.status,personalization_enabled=excluded.personalization_enabled,subscribed_at=CASE WHEN excluded.status='active' THEN CURRENT_TIMESTAMP ELSE newsletter_subscribers.subscribed_at END,unsubscribed_at=excluded.unsubscribed_at,last_site_activity_at=CURRENT_TIMESTAMP,engagement_state=CASE WHEN newsletter_subscribers.status IN('paused','unsubscribed') AND excluded.status='active' THEN 'reactivating' ELSE newsletter_subscribers.engagement_state END,reactivated_at=CASE WHEN newsletter_subscribers.status IN('paused','unsubscribed') AND excluded.status='active' THEN CURRENT_TIMESTAMP ELSE newsletter_subscribers.reactivated_at END,updated_at=CURRENT_TIMESTAMP`).bind(crypto.randomUUID(),user.id,email,active?'active':'unsubscribed',personalization?1:0,active?null:new Date().toISOString()).run();
  return json({status:active?'active':'unsubscribed',personalizationEnabled:personalization});
}
export async function unsubscribe(req,env,url){
  const row=await subscriberFromToken(env,url.searchParams.get('token'));if(!row)return json({code:'INVALID_UNSUBSCRIBE_TOKEN',message:'Link inválido ou expirado.'},400);
  if(!['GET','POST'].includes(req.method))return json({code:'METHOD_NOT_ALLOWED',message:'Método não permitido.'},405);
  await env.DB.batch([env.DB.prepare("UPDATE newsletter_subscribers SET status='unsubscribed',unsubscribed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(row.id),env.DB.prepare("UPDATE newsletter_deliveries SET status='unsubscribed' WHERE user_id=? AND status NOT IN('hard_bounce','complained')").bind(row.userId)]);
  if(req.headers.get('accept')?.includes('text/html'))return new Response('<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Newsletter desativada | SHOPLAB</title><body style="font-family:Arial;padding:48px;text-align:center;color:#173b34"><h1>Newsletter desativada</h1><p>Você não receberá novas campanhas da SHOPLAB.</p><a href="https://shoplab.com.br">Voltar à SHOPLAB</a></body></html>',{headers:{'content-type':'text/html; charset=utf-8'}});
  return json({unsubscribed:true});
}
export function effectiveInterest(score,lastInteractionAt,halfLifeDays=45){const age=Math.max(0,Date.now()-Date.parse(lastInteractionAt||0))/864e5;return Number(score||0)*Math.pow(.5,age/halfLifeDays)}
export async function recordInterest(env,userId,type,key,eventName){const weight=INTEREST_WEIGHTS[eventName]||0,entityKey=slug(key);if(!userId||!weight||!entityKey)return;await env.DB.prepare(`INSERT INTO user_interests(id,user_id,entity_type,entity_key,score,interaction_count) VALUES(?,?,?,?,?,1) ON CONFLICT(user_id,entity_type,entity_key) DO UPDATE SET score=MIN(100,user_interests.score+excluded.score),interaction_count=user_interests.interaction_count+1,last_interaction_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP`).bind(crypto.randomUUID(),userId,type,entityKey,weight).run()}
export async function calculateNewsletterRelevance(env,userId,article){const {results=[]}=await env.DB.prepare('SELECT entity_type entityType,entity_key entityKey,score,last_interaction_at lastInteractionAt FROM user_interests WHERE user_id=? ORDER BY score DESC LIMIT 100').bind(userId).all(),targets=new Set([slug(article.category),...(article.tags||[]).map(slug),...(article.products||[]).map(slug)]);let score=21;for(const interest of results)if(targets.has(interest.entityKey))score+=effectiveInterest(interest.score,interest.lastInteractionAt)*2;return Math.max(0,Math.min(100,Math.round(score)))}
export async function shouldSendNewsletter(env,subscriber,article,relevance){if(subscriber.status!=='active')return false;if(String(env.EMAIL_ENV||'').toLowerCase()==='test')return true;if(Number(subscriber.personalizationEnabled)!==0&&relevance<21)return false;const ageDays=subscriber.lastSiteActivityAt?Math.max(0,Date.now()-Date.parse(subscriber.lastSiteActivityAt))/864e5:999,daysSinceSend=subscriber.lastEmailSentAt?Math.max(0,Date.now()-Date.parse(subscriber.lastEmailSentAt))/864e5:999,minDays=ageDays<=7?.5:ageDays<=30?2:ageDays<=60?7:999;if(daysSinceSend<minDays)return false;if(ageDays>60)return false;return true}
export async function createCampaignForArticle(env,articleId,subject,enabled=true){if(!enabled)return null;const campaignId=crypto.randomUUID();await env.DB.prepare("INSERT OR IGNORE INTO newsletter_campaigns(id,article_id,status,subject) VALUES(?,?,'segmenting',?)").bind(campaignId,articleId,String(subject||'Novidade SHOPLAB').slice(0,180)).run();const campaign=await env.DB.prepare('SELECT id FROM newsletter_campaigns WHERE article_id=?').bind(articleId).first();if(env.NEWSLETTER_QUEUE)await env.NEWSLETTER_QUEUE.send({type:'segment',campaignId:campaign.id,articleId});return campaign.id}
async function segment(env,message){const article=await env.DB.prepare('SELECT id,slug,title,excerpt,category,tags,image_url imageUrl,image_alt imageAlt FROM news_articles WHERE id=? AND status=\'published\'').bind(message.articleId).first();if(!article)return;article.tags=JSON.parse(article.tags||'[]');const {results=[]}=await env.DB.prepare("SELECT id,user_id userId,email,status,personalization_enabled personalizationEnabled,last_email_sent_at lastEmailSentAt,last_site_activity_at lastSiteActivityAt FROM newsletter_subscribers WHERE status='active' AND user_id>? ORDER BY user_id LIMIT 100").bind(String(message.cursor||'')).all();let queued=0;for(const item of results){const relevance=await calculateNewsletterRelevance(env,item.userId,article);if(!(await shouldSendNewsletter(env,item,article,relevance)))continue;const deliveryId=crypto.randomUUID(),insert=await env.DB.prepare("INSERT OR IGNORE INTO newsletter_deliveries(id,campaign_id,user_id,email,relevance_score,status) VALUES(?,?,?,?,?,'queued')").bind(deliveryId,message.campaignId,item.userId,item.email,relevance).run();if(insert.meta.changes){queued++;await env.NEWSLETTER_QUEUE.send({type:'send',deliveryId})}}const hasMore=results.length===100;if(hasMore)await env.NEWSLETTER_QUEUE.send({type:'segment',campaignId:message.campaignId,articleId:message.articleId,cursor:results.at(-1).userId});await env.DB.prepare("UPDATE newsletter_campaigns SET status=?,audience_count=audience_count+?,queued_count=queued_count+?,started_at=COALESCE(started_at,CURRENT_TIMESTAMP) WHERE id=?").bind(hasMore?'segmenting':'queued',queued,queued,message.campaignId).run()}
async function sendDelivery(env,deliveryId){const delivery=await env.DB.prepare(`SELECT d.id,d.campaign_id campaignId,d.user_id userId,d.email,d.status,c.article_id articleId,c.subject,a.slug,a.title,a.excerpt,a.image_url imageUrl,a.image_alt imageAlt,p.display_name displayName FROM newsletter_deliveries d JOIN newsletter_campaigns c ON c.id=d.campaign_id JOIN news_articles a ON a.id=c.article_id LEFT JOIN user_profiles p ON p.user_id=d.user_id WHERE d.id=?`).bind(deliveryId).first();if(!delivery||!['queued','failed'].includes(delivery.status))return;const subscriber=await env.DB.prepare('SELECT id,user_id userId,email,status FROM newsletter_subscribers WHERE user_id=?').bind(delivery.userId).first();if(!subscriber||subscriber.status!=='active')return;await env.DB.prepare("UPDATE newsletter_deliveries SET status='sending',attempt_count=attempt_count+1 WHERE id=? AND status IN('queued','failed')").bind(delivery.id).run();const unsubscribeToken=await token(env,subscriber),unsubscribeUrl=`${publicOrigin(env)}/api/v1/newsletter/unsubscribe?token=${encodeURIComponent(unsubscribeToken)}`,articleUrl=`${publicOrigin(env)}/noticias/${encodeURIComponent(delivery.slug)}`,name=String(delivery.displayName||'').trim().split(/\s+/)[0],intro=name?`${esc(name)}, essa novidade pode te interessar.`:'Essa novidade pode te interessar.',mediaOrigin=String(env.PUBLIC_MEDIA_URL||'https://shoplab.bidjorysamuel.workers.dev').replace(/\/+$/,''),image=delivery.imageUrl?new URL(delivery.imageUrl,mediaOrigin+'/').href:'';
  const html=`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">${emailBrandingHead()}</head><body class="shoplab-email-body" style="margin:0;background:#eef4f2;font-family:Arial,Helvetica,sans-serif;color:#173b34"><table role="presentation" width="100%"><tr><td align="center" style="padding:24px 12px"><table role="presentation" width="100%" style="max-width:620px;background:#fff;border:1px solid #dfe9e6;border-radius:18px;overflow:hidden"><tr><td style="background:#fff;padding:24px 30px;border-bottom:1px solid #dfe9e6">${emailLogo({origin:publicOrigin(env)})}</td></tr><tr><td style="padding:30px"><p style="font-size:17px;line-height:1.6">${intro}</p>${image?`<img src="${esc(image)}" alt="${esc(delivery.imageAlt||delivery.title)}" width="560" style="display:block;width:100%;height:auto;border-radius:12px">`:''}<h1 style="font-size:28px;line-height:1.2">${esc(delivery.title)}</h1><p style="color:#405951;line-height:1.6">${esc(delivery.excerpt)}</p><p style="text-align:center"><a href="${esc(articleUrl)}" style="display:inline-block;background:#0a7b6f;color:#fff;text-decoration:none;font-weight:700;padding:14px 24px;border-radius:10px">LER NOTÍCIA</a></p></td></tr><tr><td style="background:#f7faf9;padding:20px 30px;text-align:center;color:#71837e;font-size:12px">Você recebeu este e-mail porque ativou a newsletter da ShopLab.<br>ShopLab — Escolha melhor antes de comprar.<br><a href="${esc(unsubscribeUrl)}">Cancelar inscrição</a></td></tr></table></td></tr></table></body></html>`,text=`SHOPLAB\n\n${name?name+', e':'E'}ssa novidade pode te interessar.\n\n${delivery.title}\n${delivery.excerpt||''}\n\nLer notícia: ${articleUrl}\n\nCancelar inscrição: ${unsubscribeUrl}`;
  try{const result=await sendEmail(env,{kind:'newsletter',to:delivery.email,subject:delivery.subject,html,text,userId:delivery.userId,campaignId:delivery.campaignId,articleId:delivery.articleId,headers:{'List-Unsubscribe':`<${unsubscribeUrl}>`,'List-Unsubscribe-Post':'List-Unsubscribe=One-Click'},tags:{campaign_id:delivery.campaignId,article_id:delivery.articleId,delivery_id:delivery.id}});await env.DB.batch([env.DB.prepare("UPDATE newsletter_deliveries SET status='sent',ses_message_id=?,sent_at=CURRENT_TIMESTAMP,last_error=NULL WHERE id=?").bind(result.id,delivery.id),env.DB.prepare('UPDATE newsletter_campaigns SET sent_count=sent_count+1,status=\'sending\' WHERE id=?').bind(delivery.campaignId),env.DB.prepare('UPDATE newsletter_subscribers SET last_email_sent_at=CURRENT_TIMESTAMP WHERE user_id=?').bind(delivery.userId)])}catch(error){await env.DB.prepare("UPDATE newsletter_deliveries SET status='failed',last_error=? WHERE id=?").bind(String(error.message||error).slice(0,500),delivery.id).run();throw error}}
export async function consumeNewsletterQueue(batch,env){let sent=0;for(const message of batch.messages){try{if(message.body?.type==='segment')await segment(env,message.body);else if(message.body?.type==='send'){if(sent)await new Promise(resolve=>setTimeout(resolve,100));await sendDelivery(env,message.body.deliveryId);sent++}message.ack()}catch(error){console.error(JSON.stringify({event:'newsletter_queue_error',messageId:message.id,error:String(error.message||error)}));message.retry({delaySeconds:Math.min(900,30*Math.pow(2,Math.min(5,message.attempts||1)))})}}}
export async function adminNewsletterStats(env){
  const [subscriberStatuses,subscriberSummary,engagementStates,campaigns,readingSummary,articles]=await env.DB.batch([
    env.DB.prepare("SELECT status,COUNT(*) total FROM newsletter_subscribers GROUP BY status"),
    env.DB.prepare("SELECT COUNT(*) total,SUM(CASE WHEN status='active' THEN 1 ELSE 0 END) active,SUM(CASE WHEN status='active' AND personalization_enabled=1 THEN 1 ELSE 0 END) personalizationEnabled,SUM(CASE WHEN status='active' AND personalization_enabled=0 THEN 1 ELSE 0 END) personalizationDisabled FROM newsletter_subscribers"),
    env.DB.prepare("SELECT engagement_state engagementState,COUNT(*) total FROM newsletter_subscribers WHERE status='active' GROUP BY engagement_state ORDER BY total DESC"),
    env.DB.prepare('SELECT * FROM newsletter_campaigns ORDER BY created_at DESC LIMIT 20'),
    env.DB.prepare("SELECT COUNT(*) articlesPublished,COALESCE(SUM(views),0) opens,COALESCE(SUM(unique_views),0) uniqueReaders,COALESCE(SUM(read_50),0) read50,COALESCE(SUM(read_90),0) read90,COALESCE(SUM((SELECT COALESCE(SUM(s.completes),0) FROM news_article_stats_daily s WHERE s.article_id=news_articles.id)),0) completed FROM news_articles WHERE status='published'"),
    env.DB.prepare("SELECT a.id,a.slug,a.title,a.published_at publishedAt,a.views opens,a.unique_views uniqueReaders,a.read_50 read50,a.read_90 read90,COALESCE((SELECT SUM(s.completes) FROM news_article_stats_daily s WHERE s.article_id=a.id),0) completed FROM news_articles a WHERE a.status='published' ORDER BY datetime(a.published_at) DESC LIMIT 20")
  ]);
  const counts=Object.fromEntries((subscriberStatuses.results||[]).map(x=>[x.status,Number(x.total)])),summary=subscriberSummary.results?.[0]||{},reading=readingSummary.results?.[0]||{},active=Number(summary.active||0),opens=Number(reading.opens||0);
  return {subscribers:counts,subscriberSummary:{total:Number(summary.total||0),active,personalizationEnabled:Number(summary.personalizationEnabled||0),personalizationDisabled:Number(summary.personalizationDisabled||0),personalizationRate:active?Number(summary.personalizationEnabled||0)*100/active:0},engagement:(engagementStates.results||[]).map(item=>({...item,total:Number(item.total||0)})),reading:{articlesPublished:Number(reading.articlesPublished||0),opens,uniqueReaders:Number(reading.uniqueReaders||0),read50:Number(reading.read50||0),read90:Number(reading.read90||0),completed:Number(reading.completed||0),openTo50Rate:opens?Number(reading.read50||0)*100/opens:0,openTo90Rate:opens?Number(reading.read90||0)*100/opens:0,completionRate:opens?Number(reading.completed||0)*100/opens:0},articles:(articles.results||[]).map(item=>({...item,opens:Number(item.opens||0),uniqueReaders:Number(item.uniqueReaders||0),read50:Number(item.read50||0),read90:Number(item.read90||0),completed:Number(item.completed||0)})),campaigns:campaigns.results||[]}
}
